version: '3'
services:
  backend:
    build: app
    expose:
      - "8000"
    volumes:
      - ./app/static:/opt/app/static:rw
      - ./app/media:/opt/app/media:rw
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
      - ./app/static:/data/static:ro
    depends_on:
      - backend
    ports:
      - "8000:80"

  db:
    image: postgres:latest
    volumes:
      - ./db:/var/lib/postgresql/data:rw
    env_file:
      - .env
    expose:
      - "5432"
volumes:
  db: