version: '3'
services:
  backend:
    build: app
    expose:
      - "8000"
    volumes:
      - ./app/static:/opt/app/static
    env_file:
      - .env

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - ./app/static:/data/static:ro
    depends_on:
      - backend
    ports:
      - "80:80"